#!/bin/bash

# Switch the displays around because the default state is for them to be reversed.
xrandr --output DP-2 --left-of DVI-I-1 --mode 2560x1440

# Change the background image using 'feh'
feh --bg-scale "$HOME/.xmonad/wallpaper.jpg"

# Increase the kebyoard repeat rate and decrease the repeat time.
xset r rate 200 60

# Run the screensaver so I can lock it.
nohup xscreensaver -no-splash & > /dev/null

# Run a compositer to make things a little prettier.

if [ ! -z "$(ps aux | grep compton | grep -v grep)" ] ; then
  killall compton
fi

nohup compton --backend glx & > /dev/null

# Set the cursor to not be a big X
xsetroot -cursor_name left_ptr
