#!/bin/bash

common() {
  # Startup commands common to all the hosts.
  xsetroot -cursor_name left_ptr
  xset r rate 200 60
}

hostname_rahm1() {
  # Startup commands specific to my worktop.
  xinput set-prop "TPPS/2 Elan TrackPoint" "Coordinate Transformation Matrix" 3 0 0 0 3 0 0 0 1
  xinput set-prop "SYNA8004:00 06CB:CD8B Touchpad" "Coordinate Transformation Matrix" 3 0 0 0 3 0 0 0 1

  if [ -z "$(ps aux | grep compton | grep -v grep)" ] ; then
    __GL_SYNC_TO_VBLANK=1 nohup compton --backend=glx &>/dev/null &
  fi

  feh --bg-scale "$HOME/wp.jpg"
}

hostname_photon() {
  # Startup commands specific to my desktop.

  if [ -z "$(ps aux | grep compton | grep -v grep)" ] ; then
    __GL_SYNC_TO_VBLANK=1 nohup compton --backend=glx &>/dev/null &
  fi
  # xrandr --output DVI-I-1 --right-of DP-5 --mode 2560x1440
  feh --bg-scale "/usr/share/backgrounds/archlinux/mountain.jpg"
}


common

xrdb "$HOME/.Xresources"
hostname_fn="hostname_$(cat /etc/hostname)"

if [[ "$(type -t "$hostname_fn")" == function ]] ; then
  "$hostname_fn" 
fi
