#!/bin/bash

case "$(uname -a)" in
  *-arch*) exec echo '<fn=5><fc=#1785bd></fc></fn>' ;;
  *Debian*) exec echo '<fn=5><fc=#c00649></fc></fn>' ;;
  *Ubuntu*) exec echo '<fn=5><fc=#ff8888></fc></fn>' ;;
  *Linux*)  exec echo '<fn=5><fc=#ffffff></fc></fn>' ;;
  *BSD*)    exec echo '<fn=5><fc=#ff4444></fc></fn>' ;;
esac
